name: CI
on: [push]

jobs:
  dynamic_security_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name : Start containers
      run : docker-compose -f "docker-compose.yml" up -d --build

    - name: Run Nuclei
      uses: projectdiscovery/nuclei-action@main
      with:
        target: "http://localhost"
        flags: "-severity critical,high,medium,low -stats"
        github-report: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name : Stop containers
      if : always()
      run : docker-compose -f "docker-compose.yml" down

  
  code_security_semgrep:
      runs-on: ubuntu-latest
      name: Semgrep tutorial
      steps:
        - uses: actions/checkout@v2
        - name : code Security
          run: pip3 install semgrep && semgrep  --config "auto"  --error
          shell: bash
  
  burp_ka_scanner:
      runs-on: ubuntu-latest
      name: Dastardly demo
      steps:
        - name: Run Dastardly Action Step
          continue-on-error: true                        # This allows subsequent steps to run even if this step fails
          uses: PortSwigger/dastardly-github-action@main
          with:
            target-url: 'https://ginandjuice.shop'

        # You can replace this next step with any JUnit XML parser of your choosing
        - name: Publish Test Report
          if: always()                                    # Forces this step to always run
          uses: mikepenz/action-junit-report@v3
          with:
            report_paths: '**/dastardly-report.xml'       # You need to update this path if you pass in a different output filename to the Dastardly action
            require_tests: true



  # zap_basline_and_active_scan:
  #     runs-on: ubuntu-latest
  #     steps:
  #     - uses: actions/checkout@v2


  #     - name : Start containers
  #       run : docker-compose -f "docker-compose.yml" up -d --build

      
  #     - name : ZAP baseline scan
  #       uses: zaproxy/action-baseline@v0.7.0
  #       with:
  #        target: "http://localhost"
  #        token :  ${{ secrets.GITHUB_TOKEN }}

  #     - name : Zap Active Scan
  #       uses: zaproxy/action-full-scan@v0.4.0
  #       with:
  #         target: "http://localhost"
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name : Stop containers
  #       if : always()
  #       run : docker-compose -f "docker-compose.yml" down

      



